// var Height = prompt('Enter the height');
// var Width = prompt('Enter the width');
// var area = Height * Width;
// document.write('area = ' + area);
let inputWidth = prompt('Enter the width');
let inputHeight = prompt('Enter the height');
let width = parseInt(inputWidth);
let height = parseInt(inputHeight);
let area = width * height;
document.write('Area HCN la: ' + area);
